name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          npm install
          npm run build
        working-directory: ./Users/robsonbellizari/Durli-Eco

      - name: Deploy to Server
        run: |
          # Comandos para implantar seu aplicativo no servidor
          # Pode ser um script de implantação personalizado
        working-directory: ./Users/robsonbellizari/Durli-Eco
